name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run container
        run: |
          # Build the container
          docker build -t builder .
          
          # Run the container with volume mount
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            builder \
            /bin/sh -c "make distclean && DIST_AS_EZS=yes make dist"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/plugins/rabbitmq_lvc_exchange-*.ez
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
